routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [BlogController::class, 'index'])->name('homePage');

Route::get('/category/{id}', [BlogController::class, 'getPostsByCategory'])->name('getPostsByCategory');

Route::get('/category/{category_id}/{post_id}', [BlogController::class, 'getPost'])->name('getPost');

Route::get('add/', [BlogController::class, 'add'])->middleware('auth');

Route::post('add/', [BlogController::class, 'create']);

Route::get('edit/{post_id}', [BlogController::class, 'edit'])->name('editPost')->middleware('auth');

Route::post('edit/{post_id}', [BlogController::class, 'update']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['role:admin'])->prefix('admin_panel')->group(function () {
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class, 'index'])->name('homeAdmin');
    Route::resource('category', \App\Http\Controllers\Admin\CategoryController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function posts(){
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.category.index', [
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new = new Category();

        $new->title = $request->title;
        $new->save();

        return redirect()->back()->withSuccess('Категория была добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin-layout')

@section('title', 'Все категории')

@section('content')
    <section class="content">
        <div class="container-fluid">

            @if(session('success'))
                <div class="alert alert-success">{{session('success')}}</div>
            @endif

            <div class="card card-primary">
                <form action="{{ route('category.store') }}" method="post">
                    @csrf

                    <div class="card-body">
                        <div class="form-group">
                            <label for="title">Название</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="" required>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin-layout')

@section('title', 'Список категорий')

@section('content')
    <section class="content">
        <div class="container-fluid">

            <div class="row mb-4">
                <div class="col-12">
                    <a href="{{ route('category.create') }}" class="btn btn-info">Добавить</a>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" role="grid"
                           aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                colspan="1"
                                aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">
                                Название
                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($categories as $category)
                            <tr class="odd">
                                <td class="dtr-control sorting_1" tabindex="0">{{$category->title}}</td>
                            </tr>
                        @endforeach

                    </table>
                </div>
            </div>
        </div>
        </div>
    </section>
@endsection